frase=input("Digite uma palavra ou uma frase: ")
fraseM=frase.lower()
espaco=fraseM.count(' ')
vogalA=fraseM.count('a')
vogalE=fraseM.count('e')
vogalI=fraseM.count('i')
vogalO=fraseM.count('o')
vogalU=fraseM.count('u')
print(f"Na frase ({frase}) temos:")
print(f"Espaços: {espaco};\nVogal A: {vogalA};\nVogal E: {vogalE};\nVogal I: {vogalI};\nVogal O: {vogalO};\nVogal U: {vogalU}.")